name: Windows Docker Container CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: sajigeorgejoe/my_windows_python_demo_container
  IMAGE_TAG: v1
  
jobs:

  build_image:
    name: Build the docker image and push it
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platform: windows/amd64
          tags: ${{ env.IMAGE_TAG }}
